# Open an interactive ssh session to this Windows runner: the Windows OpenSSH server, key auth only
# for the public keys of the GitHub account that dispatched the run, reached through a cloudflared
# quick tunnel (no inbound port, no secret, nothing to register). Writes <OutDir>\address.txt with
# three lines - the trycloudflare hostname, the ssh command to run locally, and the hold file whose
# deletion ends the session - which the workflow uploads as an artifact, because a job's log is not
# readable through the API while the job runs.
#
#   pwsh scripts/graalvm/win-ssh.ps1 -Actor <github actor> -OutDir <dir> -HoldFile <path>
#
# This exists because tmate, which does the same job on linux/macOS, hangs forever on windows-2022
# (see "debug_ssh is linux/macOS only" in docs/journal/windows-llvm-backend.md).
param([Parameter(Mandatory)][string]$Actor, [Parameter(Mandatory)][string]$OutDir, [Parameter(Mandatory)][string]$HoldFile)
$ErrorActionPreference = 'Stop'
$sw = [Diagnostics.Stopwatch]::StartNew()
function Log($m) { Write-Host ("[win-ssh {0,6:N1}s] {1}" -f $sw.Elapsed.TotalSeconds, $m) }
New-Item -ItemType Directory -Force $OutDir | Out-Null

# Every file written here is read by bash or by sshd, so: LF and no BOM. A CR would end up inside
# the value of the line it terminates (`export FOO='bar'<CR>` exports "bar\r").
function Write-LfFile([string]$Path, [string[]]$Lines) {
  [IO.File]::WriteAllText($Path, (($Lines -join "`n") + "`n"), (New-Object Text.UTF8Encoding $false))
}

# 1. OpenSSH server. Key auth only, for the dispatching account's keys: this repository is public,
#    and while the tunnel hostname is only in an artifact, it is not a secret either.
$cap = Get-WindowsCapability -Online -Name 'OpenSSH.Server*' | Select-Object -First 1
Log "OpenSSH.Server capability $($cap.Name): $($cap.State)"
if ($cap.State -ne 'Installed') {
  # The windows-2022 image does not ship it; the install measures 40 s. Bounded all the same, so
  # that a DISM call that hangs cannot eat the step's timeout - the way out is then MSYS2's openssh
  # package (see the journal entry for this script).
  $job = Start-Job { param($n) Add-WindowsCapability -Online -Name $n } -ArgumentList $cap.Name
  if (-not (Wait-Job $job -Timeout 180)) {
    Stop-Job $job
    throw "Add-WindowsCapability $($cap.Name) did not finish within 180 s; fall back to MSYS2 openssh"
  }
  Receive-Job $job | Out-Null
  Log "installed $($cap.Name)"
}

$keys = @((Invoke-WebRequest -UseBasicParsing "https://github.com/$Actor.keys").Content -split "`r?`n" |
          Where-Object { $_.Trim() })
if (-not $keys) { throw "no public keys on github.com/$Actor; the session would be unusable" }
Log "$($keys.Count) public key(s) from github.com/$Actor"

# StartupType first: a freshly installed capability can leave the service disabled, and
# Start-Service then refuses. The first start writes the default sshd_config and the host keys.
Set-Service -Name sshd -StartupType Manual
Start-Service sshd
Stop-Service sshd

# sshd_config ends in a `Match Group administrators` block that points AuthorizedKeysFile at
# administrators_authorized_keys, and runneradmin is an administrator - so that is the file.
$ak = 'C:\ProgramData\ssh\administrators_authorized_keys'
Write-LfFile $ak $keys
icacls $ak /inheritance:r /grant 'Administrators:F' /grant 'SYSTEM:F' | Out-Null
$cfg = 'C:\ProgramData\ssh\sshd_config'
(Get-Content $cfg) -replace '^#?PasswordAuthentication .*', 'PasswordAuthentication no' `
                   -replace '^#?PubkeyAuthentication .*', 'PubkeyAuthentication yes' | Set-Content $cfg

# Git bash as the login shell. DefaultShellCommandOption matters as much as DefaultShell: without
# it sshd passes cmd.exe's `/c` to the shell, so `ssh <host> '<command>'` runs nothing.
$bash = 'C:\Program Files\Git\bin\bash.exe'
if (-not (Test-Path $bash)) { throw "no Git bash at $bash" }
New-Item -Path 'HKLM:\SOFTWARE\OpenSSH' -Force | Out-Null
New-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSSH' -Name DefaultShell -Value $bash -PropertyType String -Force | Out-Null
New-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSSH' -Name DefaultShellCommandOption -Value '-c' -PropertyType String -Force | Out-Null
New-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSSH' -Name DefaultShellEscapeArguments -Value 0 -PropertyType DWord -Force | Out-Null

# 2. The step environment (the MSVC variables, GRAALVM_HOME, JAVA_HOME, MX_PATH, MX_URLREWRITES,
#    GITHUB_WORKSPACE, ...) for the ssh shells: sshd is a service and knows nothing of it.
#    BASH_ENV, set machine-wide before sshd starts so that sshd's children inherit it, covers
#    `ssh <host> '<command>'`, which reads neither .bash_profile nor .bashrc; the two dot files
#    cover interactive logins, where bash ignores BASH_ENV.
$envFile = Join-Path $env:USERPROFILE '.gha-env.sh'
$skip = 'PATH|HOME|SHELL|TERM|PWD|OLDPWD|SHLVL|PROMPT|_'
$lines = @('# generated by scripts/graalvm/win-ssh.ps1 - the environment of the workflow step',
           '# that opened this session. Guarded, because BASH_ENV re-sources it in every subshell.',
           'if [ -z "${GHA_ENV_SOURCED:-}" ]; then',
           'export GHA_ENV_SOURCED=1')
$lines += Get-ChildItem env: |
  Where-Object { $_.Name -match '^[A-Za-z_][A-Za-z0-9_]*$' -and $_.Name -notmatch "^($skip)$" -and
                 $_.Value -notmatch "[`r`n]" } |
  ForEach-Object { "export $($_.Name)='$($_.Value -replace "'", "'\''")'" }
# PATH separately: bash needs the POSIX form of the Windows list, which is what a `shell: bash`
# step gets (the MSYS runtime converts the inherited PATH; an `export PATH='C:\...;C:\...'` here
# would leave the session without so much as `ls`).
$lines += @("__gha_win_path='$($env:PATH -replace "'", "'\''")'",
            'PATH="$(cygpath -up "$__gha_win_path" 2>/dev/null || echo "$PATH"):$PATH"',
            'export PATH; unset __gha_win_path',
            'fi')
Write-LfFile $envFile $lines
foreach ($rc in @('.bash_profile', '.bashrc')) {
  [IO.File]::AppendAllText((Join-Path $env:USERPROFILE $rc),
    "`nsource ~/.gha-env.sh`ncd `"`$GITHUB_WORKSPACE`" 2>/dev/null || true`n",
    (New-Object Text.UTF8Encoding $false))
}
[Environment]::SetEnvironmentVariable('BASH_ENV', ($envFile -replace '\\', '/'), 'Machine')

Start-Service sshd
Log "sshd $((Get-Service sshd).Status), DefaultShell=$bash, BASH_ENV=$envFile"

# 3. cloudflared quick tunnel to port 22. The hostname shows up in its log within seconds; the
#    caller reaches it with `ssh -o ProxyCommand='cloudflared access tcp --hostname %h'`.
$cf = Join-Path $OutDir 'cloudflared.exe'
Invoke-WebRequest -UseBasicParsing 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe' -OutFile $cf
$log = Join-Path $OutDir 'cloudflared.log'
Start-Process -FilePath $cf -ArgumentList 'tunnel','--no-autoupdate','--url','tcp://localhost:22','--logfile',$log -WindowStyle Hidden
$host_ = $null
foreach ($i in 1..60) {
  Start-Sleep 2
  if (Test-Path $log) {
    $m = Select-String -Path $log -Pattern 'https://([a-z0-9-]+\.trycloudflare\.com)' | Select-Object -First 1
    if ($m) { $host_ = $m.Matches[0].Groups[1].Value; break }
  }
}
if (-not $host_) { if (Test-Path $log) { Get-Content $log }; throw 'cloudflared did not publish a trycloudflare hostname' }

# 4. Publish. The private key stays with the caller; nothing in address.txt is secret.
Set-Content -Path $HoldFile -Value 'delete me to end the session'
$cmd = "ssh -o ProxyCommand=""cloudflared access tcp --hostname %h"" -o StrictHostKeyChecking=no runneradmin@$host_"
Write-LfFile (Join-Path $OutDir 'address.txt') @($host_, $cmd, $HoldFile)
Log 'address.txt:'
Get-Content (Join-Path $OutDir 'address.txt')
